### ISSUE TITLE
In 1-Language, All-Meanings form, add column of links to GitHub Wiki meaning descriptions

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/IELex2-CognaC#42]

**Comment by runjak** [comment]
After catching up on this with  @cormacanderson I understood again what this is about:
* Add a field to the meanings list under `wordlist/all/` that allows to add a link to the GitHub wiki pages for the meanings.
* Provide links with `target="_blank"` when a meaning is mentioned in the tables.
  These links could have the GitHub icon as an image.
* If possible add a migration to automatically add in some/most of the links for meanings to GitHub.

**Comment by PaulHeggarty** [comment]
Yes, to clarify, this is actually not about the header bar, so I will remove that label.  The issue description here is too ambiguous, so I will correct it now, too.
(We do want a similar link in the header bar for both 1-meaning views, ie all languages for 1 meaning, and all cognate sets for 1 meaning, but that is different, and should really be a separate issue, which I'll create shortly)
This issue requests that in the 1-Language, All-Meanings form, immediately after the meaning name column there should be an external link icon, to take readers to the GitHub wiki page for that specific meaning.  This should be something relatively quick and easy to implement.

**Comment by runjak** [comment]
I have a solution for this that works `90%` of the times.
The problem is that some meanings aren't simply named in the form of `<meaningName>` in the wiki, but instead have a name like `01-EXCLUDE-<meaningName>`. In these cases the links won't work because the site would need to know about the different URLs before displaying the links and that would introduce a bit more work to be done.
I will roll out the feature like this for now so that the general problem of this issue is solved.
