### ISSUE TITLE
Sort Cognate Classes table by Alias letter, not by ID number

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/IELex2-CognaC#54]

**Comment by runjak** [comment]
With hg commit `9ce3cbb48a222addf2e46759f5c17c1382b58c2e` I've set the order to the alias field.
This is essentially a big step towards the desired order, but isn't 100% the wanted outcome as alias `Aa` now comes after `A` instead of after `Z`.
To improve this ordering is an issue of lower priority and I'll therefore adjust the urgency label.
