### ISSUE TITLE
Add fields for [author] and [reviewer] in the languages table

### ISSUE THREAD

**Issue by cormacanderson** [lingdb/IELex2-CognaC#59]

**Comment by PaulHeggarty** [comment]
Just to clarify, these should be, as usual, not just new fields in the Languages table in the database, but also the corresponding new columns in the Languages form on the website.
You can take it as read, Jakob, that by default when we ask for new fields in a table, we also want new corresponding columns in the relevant forms on the website, so that we can enter data into these new fiedls.
